### ISSUE TITLE
Missing `TxOutput -> datum` in utxorpc response

### ISSUE THREAD

**Issue by alekswithakayy** [txpipe/dolos#145]
The u5c spec indicates that each `TxOutput` should have a datum value associated with it. These are notably absent in blocks fetched from Dolos: [6783262.json](https://github.com/txpipe/dolos/files/13824159/6783262.json)

There are datums in the `WitnessSet -> plutus_datums` and each `TxOutput` does have a `datum_hash` however it's not obvious which datums correspond to which datum hash.

**Comment by scarmuega** [comment]
the datum payload is now available within the structure of the utxo.
