### ISSUE TITLE
Compiling Dolos on non-standard platforms

### ISSUE THREAD

**Issue by Quantumplation** [txpipe/dolos#213]
I'm running NixOS, where we have to explicitly declare system dependencies like OpenSSL, etc.

It'd be nice if the system dependencies were documented somewhere, ex: for those who need to install them, or who want to create a nix-shell or something similar.

(Note: I am *not* recommending you add a nix shell or nix flake to this repo; I am very anti-nix in general, despite running NixOS lol)

Specifically, in my case, I was getting compilation errors related to the following:
- pkg-config
- openssl
- libclang

I'm now unable to get the exact failure logs, since my machine crashed, but once I'm able to i'll share those here as well.

**Comment by scarmuega** [comment]
@Quantumplation I believe that after moving to rustls, there are no extra build dependencies other than the rust toolchain. I manage to do a successful build but I would appreciate if you could confirm.

**Comment by scarmuega** [comment]
closing as solved
