### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by SebastienGllmt** [txpipe/dolos#394]
It would be nice if I could install Dolos from an NPM package. The benefit is that Paima would be able to download Dolos for you easily instead of telling users to go through the Dolos setup steps

The Dolos package is fortunately fairly small (~25MBs unzipped) so this shouldn't be an issue bandwidth-wise

If want a simple solution, you can just copy-paste the setup I did for yaci-devkit [here](https://github.com/bloxbean/yaci-devkit/pull/85)

However, given that Dolos is written in Rust, another option is to use the same approach hardhat used which is to [setup napi](https://github.com/NomicFoundation/edr/blob/907eda356195e7fdb3cfb35a55158fb160769c38/book/src/02_development/04_update_napi_targets.md?plain=1) to generate all the packages for you for all the build options

**Comment by scarmuega** [comment]
@SebastienGllmt we've enabled the npm installer option. Next release will attempt to publish Dolos as an npm package.
