### ISSUE TITLE
gRPC: `readParams` fails on localhost networks

### ISSUE THREAD

**Issue by SebastienGllmt** [txpipe/dolos#403]
When running the `readParams` u5c query, the line [here](https://github.com/txpipe/dolos/blob/main/src/serve/grpc/query.rs#L266) will fail because it calls into [this Pallas function](https://github.com/txpipe/pallas/blob/9133163b7368dd7597ec6f51c5551aafe2a01ef8/pallas-traverse/src/wellknown.rs#L117) that only supports known networks

**Comment by scarmuega** [comment]
solved by #410
