### ISSUE TITLE
`cargo run daemon` fails to start

### ISSUE THREAD

**Issue by SebastienGllmt** [txpipe/dolos#405]
If you try and use `cargo run daemon`, you get the following error

```
thread 'main' panicked at /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:86:9:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```

Note that other commands (ex: `cargo run sync`) do work

**Comment by scarmuega** [comment]
@SebastienGllmt I can't reproduce.

- Could you share your config?
- Is this running from latest `main` branch without modification?

**Comment by SebastienGllmt** [comment]
Closing this issue because I realize now this was caused by https://github.com/txpipe/dolos/pull/400/files#r1894279172
